#FAM Client Interface Server Config file

# List of memory servers that is associated with metadata manager.
#memsrv_ip :
#- 0:<ip_address_1>
#- 1:<ip_address_2>
#- 3:<ip_address_3>
#- 2:<ip_address_4>
memsrv_ip :
- 0:127.0.0.1

# metadata manager ip address < this can also be an array right?>
#metadata_ips:
#- 0:<md_ ip_address_1>
#- 1:<md_ ip_address_2>
metadata_ips:
- 0:127.0.0.1

