# PE config file

# IP address of CIS server 
fam_client_interface_server_ip: 127.0.0.1

# Port to be used by OpenFAM  to connect to CIS Server
fam_client_interface_server_port: 8787

# Fam thread model: default is single-threaded(single). Other option is multi-threaded(multiple)
FamThreadModel : "single"

# Libfabric provider to be used by OpenFAM libfabric datapath operations; default is sockets. It could be verbs/omnipath
provider : "sockets"

# OpenFAM model to be used; default is "memory_server", Other option is  "shared_memory".
openfam_model : "memory_server"

# Runtime option used for OpenFAM; default is  "PMIX". Other options is "PMI2"
runtime : "PMIX"

# Client Interace Type for OpenFAM; default is "direct". Other option is "rpc"
client_interface_type : "direct" 
